services:
  pokedex:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex-app
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
